receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 1000
    timeout: 3s
  memory_limiter:
    limit_mib: 1500
    spike_limit_mib: 500

exporters:
  clickhouse:
    endpoint: tcp://ch-node-a.us-west1-a.c.foyer-work.internal:9000,tcp://ch-node-b.us-west1-b.c.foyer-work.internal:9000
    database: otel
    ttl: 0
    timeout: 10s
    sending_queue:
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    username: default
    password: gitgudmfs
    create_schema: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
